[2022-02-01 08:08:29,047] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcp_ingest_fhv.download_dataset_task scheduled__2019-01-02T05:00:00+00:00 [queued]>
[2022-02-01 08:08:29,058] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcp_ingest_fhv.download_dataset_task scheduled__2019-01-02T05:00:00+00:00 [queued]>
[2022-02-01 08:08:29,059] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 08:08:29,059] {taskinstance.py:1239} INFO - Starting attempt 3 of 3
[2022-02-01 08:08:29,060] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 08:08:29,073] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-01-02 05:00:00+00:00
[2022-02-01 08:08:29,078] {standard_task_runner.py:52} INFO - Started process 312 to run task
[2022-02-01 08:08:29,082] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcp_ingest_fhv', 'download_dataset_task', 'scheduled__2019-01-02T05:00:00+00:00', '--job-id', '543', '--raw', '--subdir', 'DAGS_FOLDER/dag_***_gcp_fhv.py', '--cfg-path', '/tmp/tmp01mc1nr4', '--error-file', '/tmp/tmpq7tce13_']
[2022-02-01 08:08:29,084] {standard_task_runner.py:77} INFO - Job 543: Subtask download_dataset_task
[2022-02-01 08:08:29,140] {logging_mixin.py:109} INFO - Running <TaskInstance: gcp_ingest_fhv.download_dataset_task scheduled__2019-01-02T05:00:00+00:00 [running]> on host 78d49910abc7
[2022-02-01 08:08:29,188] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-02-01 08:08:29,212] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcp_ingest_fhv
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T05:00:00+00:00
[2022-02-01 08:08:29,214] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-01 08:08:29,215] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2019-01.csv > /opt/***/output_2019-01.csv']
[2022-02-01 08:08:29,227] {subprocess.py:85} INFO - Output:
[2022-02-01 08:38:57,767] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-01 08:38:58,168] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=gcp_ingest_fhv, task_id=download_dataset_task, execution_date=20190102T050000, start_date=20220201T080829, end_date=20220201T083858
[2022-02-01 08:38:58,375] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
